### PR TITLE
remove the unused tempfile dep

### PR DESCRIPTION
**Pull request by sylvestre**
cargo +nightly udeps

### CODE REVIEW

**Comment by sylvestre** [comment]
udeps is wrong:

```
   Compiling findutils v0.2.0 (/home/runner/work/findutils/findutils)
error[E0463]: can't find crate for `tempfile`
Error:   --> src/lib.rs:12:1
   |
12 | extern crate tempfile;
   | ^^^^^^^^^^^^^^^^^^^^^^ can't find crate

```

**Comment by tertsdiepraam** [comment]
Actually, I think udeps was sort of right. The crate is only used in tests and should probably be a dev-dependency instead of a normal dependency.

**Comment by sylvestre** [comment]
right, fixed :)

**Comment by sylvestre** [comment]
https://github.com/uutils/findutils/pull/135

**Pull request closed without merging**
