### PR TITLE
Provide GNU test comparison comments for PRs in Github Actions.

### PR DESCRIPTION
**Pull request by hanbings**
link: https://github.com/uutils/findutils/issues/360

Add the PR comment code to `compat.yml`.
But I don't have a good way to test this code yet, so I'm setting it to `Daft` for now.

### CODE REVIEW

**Comment by sylvestre** [comment]
nice !
could you please fix the conflict? thanks

**Comment by sylvestre** [comment]
Testing is hard, don't hesitate if you need to land it to test it further

**Comment by hanbings** [comment]
> Testing is hard, don't hesitate if you need to land it to test it further

It seems that the compatibility information in `Annotations` is extracted correctly, but Actions gets a 403 unauthorized error when posting a comment. I guess the `Token` is not valid. Do we have a `Secret` named `GITHUB_TOKEN` or another `Secret` with comment permissions set in the repo?

and... I'm sorry for spending so much time testing.

**Comment by sylvestre** [comment]
@tertsdiepraam do you remember if it can be tested inside a PR or it needs to be merged first ?

**Comment by tertsdiepraam** [comment]
I think it had to be merged...

**Comment by tertsdiepraam** [comment]
Also, I split it into 2 workflows on purpose, so that the workflow that posts the comments could have more permissions but the other workflow could be run from the PR. We should probably do the same here. See also some of the discussions and stuff around this feature in coreutils: https://github.com/uutils/coreutils/pull/4010

**Comment by hanbings** [comment]
I'm separating the code for sending PR comments into a new CI file, but Github Actions only runs the CI file that exists in the default branch. I'm not sure the code will work, can we merge this PR first and then fix the code issues?

**Comment by sylvestre** [comment]
sure, i guess it isn't a draft anymore then ?

**Comment by sylvestre** [comment]
done

**Comment by sylvestre** [comment]
it is marked as skipped ?!

https://github.com/uutils/findutils/actions/workflows/comment.yml

**Comment by hanbings** [comment]
yeah, I feel weird about that. I'm going to finish it in my fork. Thanks.

**Comment by sylvestre** [comment]
> yeah, I feel weird about that. I'll fix it in my fork. Thanks.

don't hesitate to copy what is done in the coreutils :)

**Pull request merged**
