### PR TITLE
find/time: calculate midnight with local time zone

### PR DESCRIPTION
**Pull request by NaviHX**

### CODE REVIEW

**Comment by cakebaker** [comment]
It looks like you are using some deprecated functions:
```
error: use of deprecated method `chrono::DateTime::<Tz>::date`: Use `date_naive()` instead
  --> src/find/matchers/time.rs:28:41
   |
28 |         let local_midnight = local_time.date().and_hms(0, 0, 0);
   |                                         ^^^^
   |
   = note: `-D deprecated` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(deprecated)]`

error: use of deprecated method `chrono::Date::<Tz>::and_hms`: Use and_hms_opt() instead
  --> src/find/matchers/time.rs:28:48
   |
28 |         let local_midnight = local_time.date().and_hms(0, 0, 0);
   |
```

**Comment by sylvestre** [comment]
+ it will need tests to make sure we don't regress :)

**Comment by NaviHX** [comment]
> It looks like you are using some deprecated functions:
> 
> ```
> error: use of deprecated method `chrono::DateTime::<Tz>::date`: Use `date_naive()` instead
>   --> src/find/matchers/time.rs:28:41
>    |
> 28 |         let local_midnight = local_time.date().and_hms(0, 0, 0);
>    |                                         ^^^^
>    |
>    = note: `-D deprecated` implied by `-D warnings`
>    = help: to override `-D warnings` add `#[allow(deprecated)]`
> 
> error: use of deprecated method `chrono::Date::<Tz>::and_hms`: Use and_hms_opt() instead
>   --> src/find/matchers/time.rs:28:48
>    |
> 28 |         let local_midnight = local_time.date().and_hms(0, 0, 0);
>    |
> ```

I removed the use of `DateTime::date` and `Date::and_hms` .



> * it will need tests to make sure we don't regress :)

I added a test `find::matchers::time::tests::get_local_midnight` .

**Review by hanbings — APPROVED** [review]
Looks great! Thanks!

**Pull request merged**
