### PR TITLE
exec: Handle parent directories more carefully

### LINKED ISSUE #23: -execdir fails for the root directory
```
$ ./target/debug/find -maxdepth 0 -execdir echo '{}' \;
Failed to run echo: No such file or directory (os error 2)
```

### LINKED ISSUE #28: -execdir doesn't chdir for the root
```
$ ./target/debug/find / -maxdepth 0 -execdir pwd \;
/home/tavianator/code/uutils/findutils
$ find / -maxdepth 0 -execdir pwd \;
/
```

### PR DESCRIPTION
**Pull request by tavianator**
Fixes #23, fixes #28.

### CODE REVIEW

**Comment by sylvestre** [comment]
would it be possible to add a test for this? thanks

**Comment by tavianator** [comment]
@sylvestre Done!  I added a test for #28 anyway.  #23 already had a test from an earlier fix attempt, and it now covers the same code path (`parent == Path::new("")`).

**Comment by sylvestre** [comment]
Could you please run rustfmt on these files?
thanks

**Comment by tavianator** [comment]
@sylvestre Done!

**Comment by sylvestre** [comment]
Sorry for the latency, I missed your last update :)

**Pull request merged**
